// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvgtbqfnovddstaipygy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12Z3RicWZub3ZkZHN0YWlweWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjY5NzMsImV4cCI6MjA3MjAwMjk3M30.XbD2UZxjZrksciVUwnpiRikY2DuJu6ln_ZD3g2yOqLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});